### ISSUE TITLE
WGDashboard v4.0 (was v3.1) Suggestions

### ISSUE THREAD

**Issue by donaldzou** [donaldzou/WGDashboard#129]
1. Traffic statistics function ❤️  from #101 
2. API interface ❤️  from #101 
3. Block peers without deleting it. ❤️  from #88 
4. Remove peers after a certain amount of time. ❤️  from #86 
5. Kill Switch at Sign In page. ❤️  from #85

**Comment by airgapper** [comment]
—- @donaldzou Your platform has so much expandability potential -love it!

Was having issues where peers info didn't populate. (hangs forever) Noticed  especially when two sessions accessed portal at same time. Work around was to periodically delete tinydb file , when glitched, so it could rebuild.  —- Ultimately My fix was to re-write using MongoDB.     Works fantastic now!!!       — I now have an admin and user facing portals.  —- [ Added: ] Traffic data posted to each peers Mongo account;  API overlay to allow access with NodeJS as middleware;  email user tunnel creds;  Auto ip allocation;  instant domain name for public routable IP’s;  a disabled DB field to implement granular peer tunnel control.  Working on BGP peering automation now.    —- Its fantastically  expandable.

**Comment by donaldzou** [comment]
Hi @airgapper thank you!!! The v3.0 update, I moved from tinydb to SQLite, to prevent the issue you mentioned. It was caused by race condition when more than 1 flask session is accessing the same "Configuration" page ;) And I love how you developed new features with it!

**Comment by nicedevil007** [comment]
just small tiny thing you could add to the updater

=> at the question if we want to update the wg-dashboard make the question like this [Y/n] Y in capital because it is the default setting and if some enters "Y" or "y" or "N" or "n" it should accept those letters, right now it only accepts capital letters

**Comment by donaldzou** [comment]
> just small tiny thing you could add to the updater
> 
> => at the question if we want to update the wg-dashboard make the question like this [Y/n] Y in capital because it is the default setting and if some enters "Y" or "y" or "N" or "n" it should accept those letters, right now it only accepts capital letters

Will do will do ;)

**Comment by tokon2000** [comment]
Is a backup and restore function possible?
Then this is my wish for v3.1 :)

**Comment by xiki808** [comment]
Sorry for the dump question, but how can I block a peer? I only see how to switch of the whole configuration. Thank you!

**Comment by donaldzou** [comment]
> Sorry for the dump question, but how can I block a peer? I only see how to switch of the whole configuration. Thank you!

Hi! This feature is not implement yet, but I'm planning to implement it in the next release ;) Stay tune!

**Comment by eduardorosabales** [comment]
**As a suggestion, I would like a button to be implemented to reset the statistics of the total global traffic.**

**Comment by airgapper** [comment]
Allow for multiple wireguard servers (separate boxes).  using paramiko and subprocesses.

**Comment by pradhyumk** [comment]
A Single Sign On option utilizing solutions such as SAML 2.0, OAUTH 2.0 or OpenID Connect

**Comment by bolgovrussia** [comment]
Please add traffic information to the main page.
So that you can see the configuration traffic without going into the configuration.

**Comment by bolgovrussia** [comment]
If possible, reduce the number of decimal places in the traffic display
<img width="707" alt="Xnip2022-07-02_08-07-27" src="https://user-images.githubusercontent.com/45520996/176987367-e773433c-657a-41ca-a3fc-ec84d58bb7c4.png">
.

**Comment by nicedevil007** [comment]
What about making the Endpoint IP Adress clickable?

![image](https://user-images.githubusercontent.com/17103076/185559112-6af0c788-c511-4885-bb81-74edcf41977a.png)

In my environment there are routers as a client behind that I can access from my site to configure them remotly. Would be awesome to be able to jump directly to them from the WG-Dashboard (in a new tab ofc).

**Comment by eduardorosabales** [comment]
is this project abandoned?

**Comment by donaldzou** [comment]
Nope, I’ve too busy with my main job. But I do see each issues, and planning to fix them during my vacation.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by eduardorosabales** [comment]
I hope it will be soon because we have been waiting for an update for months... and I use your system a lot and it would be unpleasant to move to another

**Comment by donaldzou** [comment]
> I hope it will be soon because we have been waiting for an update for months... and I use your system a lot and it would be unpleasant to move to another

I'm super happy that you guys been using this project. I will definitely make those update soon. But when you working 9-to-5 vs when you still at school is different ;) I hope you guys can understand that.

**Comment by nicedevil007** [comment]
Everything is fine :) for my part I just see a problem here and there what can be improved

Recently we got your Dashboard working on alma Linux… was a bit hard to figure out what the problems are without good debuging output… but well we did it 👍

we should keep this thread for suggestions now right :)

**Comment by bugsse** [comment]
First of all, awesome project! It really has potential to become something great!

Some suggestions:
I use a script that automatically generates my wireguard config. This script pulls down a list of hosts and public keys via central api, builds a wireguard config and then compares it to the installed version. If it differs, it installs the new version and reloads wireguard. This way I can deploy a new server, add it's info to the central api and within minutes it will setup a tunnel to all the other servers in the network.
This works great, but it makes it impossible for me to use WGDashboard, mainly due to the fact that WGDashboard erases all comments in the config file. I use # comments to track names and changes and since WGDashboard erases them my script detects it as a change and generates a new config. Is there a way to make WGDashboard ignore comments and just let them be?

Also, it would be nice if WGDashboard could save the "Name" field from the webinterface as a # comment in the config file. That way I could add names in the webinterface but still see them when working in console.

**Comment by nicedevil007** [comment]
I don’t use the API thing as you do but the thing with comments would be realy nice, that’s how I started with WireGuard as well, and then there was WGDashboard 😂 I guess that is one of the downsides we have right now because wgdashboard is using an internal database for its connection names and the private keys for those clients to generate the QR codes with.
But hey hope is dying last (is that right translation, guess not)

**Comment by airgapper** [comment]
@bolgovrussia 
I like the granularity of 4 decimal places, but you can always change rounding from 4 down to 2

**Comment by kryztoval** [comment]
I would love for a button that restarts an interface, in order to accept changes after creating a new peer for example, i need to turn off and then turn on an interface. but a restart button would make it so much more practical. :)

**Comment by eduardorosabales** [comment]
We have been 7 months without updates, please I do not want to see myself in the obligation to change to another project, I like this one a lot. When will we have something new?

**Comment by JanLp** [comment]
Option to rename wg0 to something else in dashboard

**Comment by JanLp** [comment]
To keep it simple, there's no need to include "Peer" in the listing

![Skærmbillede 2022-10-29 kl  16 36 28](https://user-images.githubusercontent.com/55313117/198837479-e7312b79-2cad-49f8-bcce-e5f7aaf919e2.png)

**Comment by JanLp** [comment]
> I hope it will be soon because we have been waiting for an update for months... and I use your system a lot and it would be unpleasant to move to another

Do you have any problems with current version?

**Comment by webastik** [comment]
HTTPS SSL
Please add HTTPS for WGDashboard.
And even if the SSL certificate is self-signed. It's better than no SSL at all.

**Comment by hellblue** [comment]
for https you can use nginx proxy manager there you have also SSL certifikate with Lets Encrypt

**Comment by poorp** [comment]
I suggest adding traffic quota (or limitation) for each user + expiration date.
I assume expiration date is pretty straight forward: just a simple script that auto DISABLEs (temporarily deleted but kept somewhere for re-enabling) the user's (or peer's) account.
Also by traffic quota or limitation I mean the ability to limit data usage of a peer to X GB per month. I think this can probably be done using iptables quotas and peers' internal WG IPs but I'm not sure.

**Comment by bakasovpn** [comment]
I usually use your project, I am from Central Asia and I would like to highlight the language selection function, people from other countries think they will use it too, is it possible to make a separate file with the language interface, in the future just add a new file and switch to it?
I use Google translator, I hope my thoughts will reach you.

**Comment by eduardorosabales** [comment]
Ask the creator, there will never be another update?

**Comment by donaldzou** [comment]
@eduardorosabales Yes. I'm planning to do a revamp of the backend and frontend, since it is written with Flask and jQuery (Not the best thing to do nowadays).. I'm starting on it so please bare with me.

As always, thanks all of you using my project and still using it :)

**Comment by eduardorosabales** [comment]
I use your project a lot, it has helped me a lot but improvements can be made and everything previously said here should be implemented.
More or less the estimated time you would be releasing an update

**Comment by bakasovpn** [comment]
@donaldzou
It would be nice to have an interface language; most of the words are clear.
but I would still like a choice of language

**Comment by barryboom** [comment]
> @eduardorosabales Yes. I'm planning to do a revamp of the backend and frontend, since it is written with Flask and jQuery (Not the best thing to do nowadays).. I'm starting on it so please bare with me.
> 
> As always, thanks all of you using my project and still using it :)

nice to read you are coming back to the project and look to revamp. a nice easy one to do would be promote the beta version which looks so much better and gives dark mode would be good for them who are happy with Flask etc.

**Comment by donaldzou** [comment]
if anyone is curious, I will make all the updates under the branch [v3.1-dev2023](https://github.com/donaldzou/WGDashboard/tree/v.3.1-dev2023)

**Comment by kontorskiy777** [comment]
Hello, I found a log service for WG on the website, checked its functionality, it works on the basis of handshakes, shows the time and date, user name, its external IP address from which users connected (at what time) and disconnected (at what time) .
Please consider adding this feature to your control panel, it will be very useful.
https://github.com/amitn322/wireguard

**Comment by eduardorosabales** [comment]
Luckily I've resumed work, and I'm already using your beta version, how happy I am, I would like you to put a type of quota for each peer so I could control my users by total bandwidth consumption... I would also like this counter It could be reset manually...
keep up your great work

**Comment by eduardorosabales** [comment]
@donaldzou check the previous message

**Comment by donaldzou** [comment]
> @donaldzou check the previous message

Thank you for the suggestion, I'm actually thinking that and will be implement into the new version :)

**Comment by eduardorosabales** [comment]
> > @donaldzou check the previous message
> 
> Thank you for the suggestion, I'm actually thinking that and will be implement into the new version :)

Do you think it will be ready in less than 1 month, the truth is that I need it as soon as possible, I need to be able to control by installments and reset that counter

**Comment by donaldzou** [comment]
> > > @donaldzou check the previous message
> > 
> > 
> > Thank you for the suggestion, I'm actually thinking that and will be implement into the new version :)
> 
> Do you think it will be ready in less than 1 month, the truth is that I need it as soon as possible, I need to be able to control by installments and reset that counter

Hi, I would love to finish the new update, but with my current work, school and personal life, I'm trying my best to finish it. Hope you can understand :)

**Comment by upgo7502** [comment]
Hello Dear
Please add expireation date for peers .

Thanks in advance

**Comment by upgo7502** [comment]
Hello Dear
Please add expireation date for peers .

Thanks in advance

**Comment by upgo7502** [comment]
Hello Dear
Please add expireation date for peers .

Thanks in advance

**Comment by upgo7502** [comment]
Hello Dear
Please add expireation date for peers .

Thanks in advance

**Comment by iRexyz** [comment]
For example, we should be able to choose the date when a peer will close.

Example: until 01.0.1.2025

After the specified period of time, the peer becomes deactivated.

**Comment by potap1978** [comment]
is this project abandoned?

**Comment by donaldzou** [comment]
> is this project abandoned?

Hi! No it is not ☺️ currently is university final season and I'm focusing on that so I can get the hell out of it🤣 I'm promising a new release of this project so please let me know if you have any suggestions. Thanks a lot!!

**Comment by Profik** [comment]
@donaldzou 

### When will the first release be released?

**From the wishes:**
1. Make a registration for users, where a person can download a QR CODE or a configuration file himself.
2. Make a restriction not only on traffic, but also on the date range (month) with the possibility of extension.

Thanks for the cool project. You will be a successful developer, colleague :)

**Comment by donaldzou** [comment]
> @donaldzou
> 
> ### When will the first release be released?
> **From the wishes:**
> 
> 1. Make a registration for users, where a person can download a QR CODE or a configuration file himself.
> 2. Make a restriction not only on traffic, but also on the date range (month) with the possibility of extension.
> 
> Thanks for the cool project. You will be a successful developer, colleague :)

Hi @Profik,

I'm still working on some new features and testing it :) Thank you for providing these suggestions.

> 1. Make a registration for users, where a person can download a QR CODE or a configuration file himself.
I think is a great idea but at this point the dashboard is targeted for the admin instead of facing clients. But this is definitely a good suggestion in future release.

> 2. Make a restriction not only on traffic, but also on the date range (month) with the possibility of extension.
Currently I'm implementing where the dashboard can automatically restrict or delete a peer in a specific date or data usage is over a limit. If you want to try it out for fun, you can clone my `v4.0` branch and check it out ;)

**Comment by donaldzou** [comment]
To all the people who is following this issue, I've been updating the `v4.0` branch and posting some preview on the `readme.md` of the main branch! If you're interested, you can head to the [`v4.0` branch](https://github.com/donaldzou/WGDashboard/tree/v4) or the [project](https://github.com/users/donaldzou/projects/2) and check it out :)

**Comment by donaldzou** [comment]
# Roadmap on v4.0

I will keep updating this comment :)

## Updates on the new features everyone requested 😄 

- [x] Traffic statistic on configuration page
- [x] API interface w/ API Key (Still need to finish documentation).
- [x] Block peers without deleting it (YES, we now have restrict). 🫶 to @xiki808.
- [x] Remove peer after period or condition. 🫶 to #86, @poorp, @upgo7502, @rlrexyz, @Profik .
- [x] Accept y/Y in `.wgd.sh`.  🫶 to @nicedevil007

## Still need to work on

- [ ] Backup & restore function on db and WireGuard file. 🫶 to @tokon2000
- [ ] Reset Peer or Configuration's data usage. 🫶 to @eduardorosabales 
- [ ] Email configuration, thinking of using SendGrid or MailChip to avoid the hassle of creating domain and such. 🫶 to @adrinux 
- [ ] Add traffic information on main page. 🫶 to @bolgovrussia
- [ ] Restart button for configuration. 🫶 to @airgapper
- [ ] Different language. 🫶 to @bkeenke 
- [ ] Tracking when did peer connected and disconnected. 🫶 to @kontorskiy777 
- [ ] An interface facing the client to download with QR Code: Maybe a better way is to create an unique link, that link to a page where only show the QR code and a button to download, and the link can expire at a time. 🫶 to @Profik

> New feature for `v4.0` will cut off from here, other feature will release in later releases 😃 

## Features not consider at the moment. Sorry 🥹 

- Using SSO for login: The reason is I'm trying to keep the dashboard simple and not adding 3rd party service to add more complexity. 🫶 to @pradhyumk 
- Add rounding to 2 decimals on traffic. 🫶 to @bolgovrussia 
- Parsing comments in `.conf`: I've tried to implement the function, but I can't guaranteed the stability since there are tons way of writing comments in a config file. 🫶 to @bugsse
- Remove "Peer" keyword on each peer: I'd like to keep the uniform design of each information. 🫶 to @ghost

**Comment by Profik** [comment]
> # Дорожная карта по версии 4.0
> Я буду продолжать обновлять этот комментарий :)
> 
> ## Обновления новых функций, которые все просили 😄
> * [x] Статистика трафика на странице конфигурации
> * [x] Интерфейс API с ключом API (еще необходимо завершить документацию).
> * [x] Блокировать пиров, не удаляя их (ДА, теперь у нас есть ограничение). 🫶@xiki808.
> * [x] Удалить пир после периода или условия. 🫶 Запросить [функцию, которая удаляет пиры по значению времени ](https://github.com/donaldzou/WGDashboard/issues/86)[ #86](https://github.com/donaldzou/WGDashboard/issues/86) ,[](https://github.com/donaldzou/WGDashboard/issues/86)@poorp,@upgo7502,@rlrexyz,@Profik.
> * [x] Принять y/Y в `.wgd.sh`. 🫶 к@nicedevil007
> 
> ## Еще нужно поработать
> * [ ] Функция резервного копирования и восстановления базы данных и файла WireGuard. 🫶@tokon2000
> * [ ] Сбросьте использование данных Peer или Configuration. 🫶@eduardorosabales
> * [ ] Конфигурация электронной почты, думаю использовать SendGrid или MailChip, чтобы избежать хлопот с созданием домена и т.п. 🫶 to@adrinux
> * [ ] Добавьте информацию о дорожном движении на главную страницу. 🫶 to@bolgovrussia
> * [ ] Кнопка перезагрузки для настройки. 🫶 to@airgapper
> * [ ] Другой язык. 🫶 to@bkeenke
> * [ ] Отслеживание того, когда пир подключался и отключался. 🫶 to@kontorskiy777
> * [ ] Интерфейс, обращенный к клиенту для загрузки с QR-кодом: Возможно, лучшим способом будет создание уникальной ссылки, которая ведет на страницу, где отображаются только QR-код и кнопка для загрузки, и ссылка может истечь в определенный момент времени. 🫶 to@Profik
> 
> > Новая функция `v4.0`будет отключена здесь, другие функции будут выпущены в более поздних версиях 😃
> 
> ## Функции не рассматриваются в данный момент. Извините 🥹
> * Использование единого входа для входа: Причина в том, что я пытаюсь сделать панель управления простой и не добавлять сторонние сервисы, чтобы не усложнять ее. 🫶@pradhyumk
> * Добавьте округление до 2 знаков после запятой по трафику. 🫶 to@bolgovrussia
> * Анализ комментариев в `.conf`: Я пытался реализовать функцию, но не могу гарантировать стабильность, так как существует множество способов записи комментариев в файле конфигурации. 🫶 to@bugsse
> * Удалить ключевое слово «Peer» для каждого узла: Я бы хотел сохранить единый дизайн каждой информации. 🫶 to@ghost

**Dear friend, I will install this branch for myself, I will test and write about bugs or recommendations found.**

**Comment by donaldzou** [comment]
Don't wanna spam other's inbox lol. I will close this issues and created a new issue for the road map. **Thanks all of you suggesting features throughout the last 3 years.**

![the-office-bow](https://github.com/user-attachments/assets/ff734b79-0d7e-40e0-bc41-25579f5cc45a)


✌️
