### ISSUE TITLE
Roadmap on v4.0

### ISSUE THREAD

**Issue by donaldzou** [donaldzou/WGDashboard#293]
# Roadmap on v4.0

I will keep updating this comment :)

## Updates on the new features everyone requested 😄 

- [x] Traffic statistic on configuration page
- [x] API interface w/ API Key (Still need to finish documentation).
- [x] Block peers without deleting it (YES, we now have restrict). 🫶 to @xiki808.
- [x] Remove peer after period or condition. 🫶 to #86, @poorp, @upgo7502, @rlrexyz, @Profik .
- [x] Accept y/Y in `.wgd.sh`.  🫶 to @nicedevil007

## Still need to work on

- [ ] Backup & restore function on db and WireGuard file. 🫶 to @tokon2000
- [ ] Reset Peer or Configuration's data usage. 🫶 to @eduardorosabales 
- [ ] Email configuration, thinking of using SendGrid or MailChip to avoid the hassle of creating domain and such. 🫶 to @adrinux 
- [ ] Add traffic information on main page. 🫶 to @bolgovrussia
- [ ] Restart button for configuration. 🫶 to @airgapper
- [ ] Different language. 🫶 to @bkeenke 
- [ ] Tracking when did peer connected and disconnected. 🫶 to @kontorskiy777 
- [ ] An interface facing the client to download with QR Code: Maybe a better way is to create an unique link, that link to a page where only show the QR code and a button to download, and the link can expire at a time. 🫶 to @Profik

> New feature for `v4.0` will cut off from here, other feature will release in later releases 😃 

## Features not consider at the moment. Sorry 🥹 

- Using SSO for login: The reason is I'm trying to keep the dashboard simple and not adding 3rd party service to add more complexity. 🫶 to @pradhyumk 
- Add rounding to 2 decimals on traffic. 🫶 to @bolgovrussia 
- Parsing comments in `.conf`: I've tried to implement the function, but I can't guaranteed the stability since there are tons way of writing comments in a config file. 🫶 to @bugsse
- Remove "Peer" keyword on each peer: I'd like to keep the uniform design of each information. 🫶 to @ghost

_Originally posted by @donaldzou in https://github.com/donaldzou/WGDashboard/issues/129#issuecomment-2267374588_

**Comment by Johnnykson** [comment]
> Parsing comments in .conf: I've tried to implement the function, but I can't guaranteed the stability since there are tons way of writing comments in a config file. 🫶 to @bugsse 
I suggest implementing comment analysis only for one template, choose any, so that there is generally the possibility of importing configurations, and users themselves will edit manually for this template either in the configs themselves or in the scripts that create them. I suggest choosing a template from this script https://github.com/angristan/wireguard-install

**Comment by donaldzou** [comment]
> > Parsing comments in .conf: I've tried to implement the function, but I can't guaranteed the stability since there are tons way of writing comments in a config file. 🫶 to @bugsse
> 
> I suggest implementing comment analysis only for one template, choose any, so that there is generally the possibility of importing configurations, and users themselves will edit manually for this template either in the configs themselves or in the scripts that create them. I propose to choose a template based on this script https://github.com/angristan/wireguard-install/blob/master/wireguard-install.sh

I think you gave me a direction! I'll look into it and maybe squeeze it in the `v4` release. I don't think is too hard to implement.

**Comment by Profik** [comment]
@donaldzou 
Hi! 
Is it possible for you to set a speed limit for each feast? Can you do it through the Linux Traffic Control utility?

**Comment by donaldzou** [comment]
Hi @Profik , I've used the `tc` -- Linux Traffic Control to limit speed on the entire configuration (interface), but not on specific peer. But I'm thinking, you can use the `tc` command to limit the `tx` -- transmit rate on the peer's machine (if it is running Linux as well)

**Comment by Profik** [comment]
@donaldzou 
Let's say there are 5 users (smartphones), one of them decided to watch YouTube, then he will take the entire channel, the other 4 will have brakes on the Internet. What should I do in this situation?

**Comment by donaldzou** [comment]
> @donaldzou 
> 
> Let's say there are 5 users (smartphones), one of them decided to watch YouTube, then he will take the entire channel, the other 4 will have brakes on the Internet. What should I do in this situation?

In this case you might need to look into packet capturing on your server, and if it detect any packet that is going to YouTube, then you can maybe just tc to limit the other peers to none? Just a general idea I can think of :)

**Comment by DaanSelen** [comment]
Regarding languages I can contribute Dutch.

**Comment by Profik** [comment]
@donaldzou I can offer a translation into Russian.

**Comment by donaldzou** [comment]
Closing this issue, refer to the new road map #354

**Comment by donaldzou** [comment]
Hi @DaanSelen and @Profik, if you guys are still willing to contribute localization, please visit #397 ;)
