### ISSUE TITLE
Roadmap on v4.1

### ISSUE THREAD

**Issue by donaldzou** [donaldzou/WGDashboard#354]
# Roadmap on v4.1

## Bugs need to fix

- [x] #353: Mobile UI on sign in screen
- [x] #328: Remove `[WGDashboard] wg0 Error: '[Peer]' is not in list` from gunicorn
- [x] #357: Clicking Restrict Peer now deleting the Peer configuration
- [x] #366: `sqlite3.OperationalError: cannot commit - no transaction is active` error

## Features

- [x] Different languages: `en-us`, `zh-cn`, `zh-hk`, `ru`, `nl`
- [x] #357: Bring back version number on navbar, bring back dashboard port settings, update configuration path
- [x] #352: Peer delete confirmation
- [x] #346: Add domain support on DNS
- [x] #350: Add delete function for WG config and delete peers in bulk
- [x] Backup & restore function on db and WireGuard file. 
- [x] Change Volume configuration in Docker to have multiple update routes.
- [x] #353: Add Pre-Shared Key switch
- [x] #351: Allow user to disable animation on graphs
- [x] #361: a better search function :)
- [x] Delete configuration 
- [x] Create configuration from backup 
- [x] Autostart Configuration
- [x] Show .conf without downloading #453 
- [ ] #393: Add instructions on each field

## Something to consider

- [ ] #370: Add support to AmneziaWG
- [x] #382: Add AlmaLinux & Pi OS to support
