### ISSUE TITLE
v4.2.0 Road Map

### ISSUE THREAD

**Issue by donaldzou** [donaldzou/WGDashboard#461]
## Testing on all operating system
- [x] Ubuntu 20.04 LTS
- [x] Ubuntu 22.04 LTS
- [x] Ubuntu 24.04 LTS
- [x] Ubuntu 24.10 **(New)**
- [x] Debian 12.6﻿
- [x] Debian 11.10
- [x] RHEL 9.4﻿
- [x] CentOS 9-Stream﻿
- [x] Alma Linux 9.4 (Seafoam Ocelot)﻿
- [x] Fedora 40, 39, 38﻿
- [x] Alpine Linux 3.20.2﻿
- [x] Rocky 9.4﻿
- [x] Pi OS Kernel Version: 6.6 w/ Debian 12 (Bookworm)

<hr>

- [x] A better editing method for Post/Pre Up & Down #456 
- [x] #530
- [x] UI Adjustment on editing configuration #479 
- [x] Adding certificate support? #145
- [x] Adding email support? #171 
- [x] Adding AmneziaWG? #370 
- [x] Showing the Peer's actual IP address on the UI #383
- [x] Copy configuration #322 
- [x] Pick first available IP #515 
- [x] Dropping `ifcfg` library in `dashboard.py`
- [x] Add tooltips to dropdown icons #524 
- [x] Adjust UI for notification
- [x] #545
- [x] Download Backup

<hr>

- [x] Add support to OpenBSD and FreeBSD
   - Currently I have the install commands ready for OpenBSD, but it will crash on one of the Python package #483 

<hr>

### Bugs need to fix

- [x] #522
    - need to add `... and DashboardConfig.GetConfig("Server", "auth_req")[1]` in `API_ValidateAuthentication()`
- [x] Fix accepting duplicate entry in WG Configuration files after running `wg-save` #497 
- [x] #332
- [x] #446 
- [x] When using `%i` ins Post/Pre scripts will cause error #493

**Comment by mzs114** [comment]
Please consider using some code scanning and security tools like SonarQube, Synk and others. These are free for FLOSS and will help you analyze the code quality.

**Comment by donaldzou** [comment]
> Please consider using some code scanning and security tools like SonarQube, Synk and others. These are free for FLOSS and will help you analyze the code quality.

Good suggestion, will look into it :)

**Comment by DaanSelen** [comment]
Adding certificate support? https://github.com/donaldzou/WGDashboard/issues/145

**Comment by NOXCIS** [comment]
@donaldzou @DaanSelen Here, Docker Denviorment For WGDashboard based on Ubuntu. Nothing else needs be changed just put these two files in the repo root and run compose up. AmneziaWG works out of the box.


### compose.yaml
````yaml

services:
  wireguard-dashboard:
    build:
      context: .
      dockerfile: Ubuntu.Dev.Dockerfile
    #image: donaldzou/wgdashboard:latest
    restart: unless-stopped
    container_name: wgdashboard 
    #environment:
      #- tz=                # <--- Set container timezone, default: Europe/Amsterdam.
      #- global_dns=        # <--- Set global DNS address, default: 1.1.1.1.
      #- isolate=           # <--- Set the interfaces that will disallow peer communication, default: 'none'.
      #- public_ip=         # <--- Set public IP to ensure the correct one is chosen, defaulting to the IP give by ifconfig.me.
    ports:
      - 10086:10086/tcp
      - 51820:51820/udp
    volumes:
      - conf:/etc/wireguard
      - data:/data
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun 

volumes:
  conf:
  data:


````


### Ubuntu.Dev.Dockerfile

````Dockerfile

# Compiler: Build AmneziaWG (Obfuscated Wireguard)
FROM golang:1.23.4-bookworm@sha256:ef30001eeadd12890c7737c26f3be5b3a8479ccdcdc553b999c84879875a27ce AS compiler
WORKDIR /go


RUN apt-get update && apt-get install -y --no-install-recommends \
    git make bash build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


RUN git clone --depth=1 https://github.com/amnezia-vpn/amneziawg-tools.git && \
    git clone --depth=1 https://github.com/amnezia-vpn/amneziawg-go.git
RUN cd /go/amneziawg-tools/src && make
RUN cd /go/amneziawg-go && \
    go get -u ./... && \
    go mod tidy && \
    make && \
    chmod +x /go/amneziawg-go/amneziawg-go /go/amneziawg-tools/src/wg /go/amneziawg-tools/src/wg-quick/linux.bash
RUN echo "DONE AmneziaWG"


FROM scratch AS bins
COPY --from=compiler /go/amneziawg-go/amneziawg-go /amneziawg-go
COPY --from=compiler /go/amneziawg-tools/src/wg /awg
COPY --from=compiler /go/amneziawg-tools/src/wg-quick/linux.bash /awg-quick




FROM ubuntu:latest
WORKDIR /WGDashboard
ENV TZ=UTC
EXPOSE 10086
COPY ./src /WGDashboard/

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install wireguard sudo python3 python3-venv python3-pip net-tools -y && \
    apt install iproute2 -y && \
    mkdir -p /etc/amnezia/amneziawg

# Copy AmneziaWG binaries
COPY entrypoint.sh /WGDashboard/entrypoint.sh
COPY --from=bins /amneziawg-go /usr/bin/amneziawg-go
COPY --from=bins /awg /usr/bin/awg
COPY --from=bins /awg-quick /usr/bin/awg-quick

# Install necessary tools and libraries in the final image
RUN chmod +x /WGDashboard/wgd.sh && chmod +x /WGDashboard/entrypoint.sh

RUN if [ ! -c /dev/net/tun ]; then \
    mkdir -p /dev/net && mknod /dev/net/tun c 10 200; \
fi


RUN ./wgd.sh install
# Start the script and keep it alive by tailing the logs
CMD ["/bin/bash", "-c", "/WGDashboard/wgd.sh start && tail -f /dev/null"]



````

**Comment by DaanSelen** [comment]
I dont know how important it will be but is persistency taken care of? Ill make a PR

**Comment by DaanSelen** [comment]
Perhaps also: https://github.com/donaldzou/WGDashboard/issues/511

**Comment by akhepcat** [comment]
Just upgraded from 4.1.4 to 4.2-dev  [3af84e01]   and it seems there's a gui timeout that is forcing me out of the configuration interface, even if i've been  making changes within the last 30s or so.

I don't see where anything like that is exposed in the GUI, so I'm not sure how to deal with it.

There are no messages in the error or access logs that correspond to the session timing out,  nor is journalctl  showing the actual service restarting.

**Comment by DaanSelen** [comment]
Have you tried clearing the browser cache?

**Comment by akhepcat** [comment]
> Have you tried clearing the browser cache? I am going to verify if I can reproduce tormorrow UTC.

Yep, cache cleared, cookies cleared, local storage cleared.   

Still times out in about 60 seconds after login, either with no user interaction, or while navigating.

**Comment by Arunachalamkalimuthu** [comment]
@donaldzou  Please update the documentation how to support ipv6 ip ranges

**Comment by mzs114** [comment]
I think these changes were implemented? Perhaps close as 'Completed'?
